Sun May 16 16:07:45 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:08.0 Off |                    0 |
| N/A   43C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Python 3.8.5
 16:07:45 up 10 days,  9:46,  2 users,  load average: 1,29, 2,58, 3,69
2021-05-16 16:08:00.316776: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /vol/cuda/10.2.89-cudnn7.6.4.38/lib64:/vol/cuda/10.2.89-cudnn7.6.4.38/lib:/vol/cuda/10.2.89-cudnn7.6.4.38/x86_64-linux-gnu
2021-05-16 16:08:00.317147: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Logs from runs/May16_16-07-57_cloud-vm-41-149.doc.ic.ac.ukcardiacA3C
medical.py --files /vol/biomedic2/aa16914/shared/RL_Guy/rl-medical/examples/LandmarkDetection/DQN/data/filenames/cardiac_train_files.txt /vol/biomedic2/aa16914/shared/RL_Guy/rl-medical/examples/LandmarkDetection/DQN/data/filenames/cardiac_train_landmarks.txt

Attribute : agents
Attribute : oscillations_allowed
Attribute : logger
Attribute : stats
Attribute : num_games
Attribute : num_success
Attribute : cnt
Attribute : max_num_frames
Attribute : info
Attribute : saveGif
Attribute : saveVideo
Attribute : task
Attribute : screen_dims
Attribute : dims
Attribute : multiscale
Attribute : landmarks
Attribute : width
Attribute : height
Attribute : depth
Attribute : viz
Attribute : current_episode_score
Attribute : action_space
Attribute : actions
Attribute : observation_space
Attribute : _history_length
Attribute : _loc_history
Attribute : _qvalues_history
Attribute : rectangle
Attribute : files
Attribute : filepath
Attribute : fixed_spawn
Attribute : terminal
Attribute : reward
Attribute : viewer
Attribute : _image
Attribute : _target_loc
Attribute : spacing
Attribute : filename
Attribute : action_step
Attribute : xscale
Attribute : yscale
Attribute : zscale
Attribute : _image_dims
Attribute : _location
Attribute : _start_location
Attribute : _qvalues
Attribute : _screen
Attribute : cur_dist
Attribute : id
AGENT NAME: A3C
[1m1.1: A3C[0m
TITLE  Medical
Score required to win set to infinity therefore no learning rate annealing will happen
Traceback (most recent call last):
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/Base_Agent.py", line 110, in get_trials
    try: return self.environment.unwrapped.trials
AttributeError: 'MedicalPlayer' object has no attribute 'trials'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "medical.py", line 216, in <module>
    trainer.run_games_for_agents()
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/Trainer.py", line 79, in run_games_for_agents
    self.run_games_for_agent(agent_number + 1, agent_class)
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/Trainer.py", line 117, in run_games_for_agent
    agent = agent_class(agent_config)
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/actor_critic_agents/A3C.py", line 16, in __init__
    super(A3C, self).__init__(config)
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/Base_Agent.py", line 33, in __init__
    self.rolling_score_window = self.get_trials()
  File "/vol/bitbucket/nb420/rl-medical/Deep_RL_Implementations/agents/Base_Agent.py", line 111, in get_trials
    except AttributeError: return self.environment.spec.trials
AttributeError: 'NoneType' object has no attribute 'trials'
